# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(130, 60, 641, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 781, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 101, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_FaceCollection = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_FaceCollection.setObjectName("btn_FaceCollection")
        self.verticalLayout.addWidget(self.btn_FaceCollection)
        self.btn_Train = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Train.setObjectName("btn_Train")
        self.verticalLayout.addWidget(self.btn_Train)
        self.btn_Encrypt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.verticalLayout.addWidget(self.btn_Encrypt)
        self.btn_Decrypt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        self.verticalLayout.addWidget(self.btn_Decrypt)
        self.btn_Detect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Detect.setObjectName("btn_Detect")
        self.verticalLayout.addWidget(self.btn_Detect)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.btn_FaceCollection.clicked.connect(MainWindow.btn_FaceCollection_onClicked)
        self.btn_Train.clicked.connect(MainWindow.btn_Train_onClicked)
        self.btn_Encrypt.clicked.connect(MainWindow.btn_Encrypt_onClicked)
        self.btn_Decrypt.clicked.connect(MainWindow.btn_Decrypt_onClicked)
        self.btn_Detect.clicked.connect(MainWindow.btn_Detect_onClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "人脸识别系统"))
        self.btn_FaceCollection.setText(_translate("MainWindow", "人脸采集"))
        self.btn_Train.setText(_translate("MainWindow", "训练样本"))
        self.btn_Encrypt.setText(_translate("MainWindow", "加密"))
        self.btn_Decrypt.setText(_translate("MainWindow", "解密"))
        self.btn_Detect.setText(_translate("MainWindow", "开始识别"))
